# Generated by Django 5.2.10 on 2026-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Describe this voice style')),
                ('sample_posts', models.TextField(help_text='3-5 sample posts to learn tone from')),
                ('generated_prompt', models.TextField(blank=True, help_text='AI-generated style instructions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('blog', 'Blog Article'), ('pdf', 'PDF Document'), ('text', 'Raw Text')], max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True, help_text='Extracted or pasted text')),
                ('key_insights', models.JSONField(blank=True, default=list, help_text='AI-extracted key points')),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Source',
                'verbose_name_plural': 'Content Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepurposedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('youtube', 'YouTube Community'), ('newsletter', 'Newsletter')], max_length=20)),
                ('generated_content', models.TextField(blank=True)),
                ('hook', models.CharField(blank=True, help_text='Attention-grabbing first line', max_length=500)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('thread_posts', models.JSONField(blank=True, default=list, help_text='List of thread posts')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, help_text='ID from platform after posting', max_length=255)),
                ('platform_post_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repurposed Post',
                'verbose_name_plural': 'Repurposed Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
