# Generated by Django 5.2.10 on 2026-01-22 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repurposer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_voices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repurposedpost',
            name='brand_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repurposer.brandvoice'),
        ),
        migrations.AddField(
            model_name='repurposedpost',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repurposed_posts', to='repurposer.contentsource'),
        ),
        migrations.AlterUniqueTogether(
            name='brandvoice',
            unique_together={('user', 'name')},
        ),
    ]
