# Generated by Django 5.2.10 on 2026-01-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repurposedpost',
            name='media_file',
            field=models.FileField(blank=True, help_text='Image or video file to attach', null=True, upload_to='post_media/'),
        ),
    ]
