# Generated by Django 5.2.10 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0003_repurposedpost_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repurposedpost',
            name='scheduled_for',
        ),
        migrations.AlterField(
            model_name='repurposedpost',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('youtube', 'YouTube Community'), ('newsletter', 'Newsletter'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='repurposedpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
