# Generated by Django 5.2.10 on 2026-01-28 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0004_remove_repurposedpost_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, help_text='AI prompt for generating new content on schedule')),
                ('platforms', models.JSONField(default=list, help_text="List of platforms to post to: ['youtube', 'linkedin']")),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='When to publish (for one-time) or start time (for recurring)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repurposer.brandvoice')),
                ('post', models.ForeignKey(blank=True, help_text='Existing post to schedule. Leave empty to generate from prompt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='repurposer.repurposedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Post',
                'verbose_name_plural': 'Scheduled Posts',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
