# Generated by Django 5.2.10 on 2026-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(default='free', help_text='Current subscription plan', max_length=20),
        ),
    ]
