# Generated by Django 5.2.10 on 2026-01-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repurposer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('platform_username', models.CharField(blank=True, max_length=255)),
                ('platform_name', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('platform_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repurposed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_logs', to='repurposer.repurposedpost')),
            ],
            options={
                'verbose_name': 'Posting Log',
                'verbose_name_plural': 'Posting Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
